# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 08:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Android', max_length=20, verbose_name='设备系统')),
                ('version', models.CharField(max_length=20, verbose_name='设备系统版本')),
                ('devicename', models.CharField(max_length=20, verbose_name='设备名称(deviceName)')),
                ('apppath', models.CharField(blank=True, max_length=256, null=True, verbose_name='绝对路径（设置此项后两项可不填，反之同理）')),
                ('apppackage', models.CharField(blank=True, max_length=80, null=True, verbose_name='appPackage')),
                ('appactivity', models.CharField(blank=True, max_length=80, null=True, verbose_name='appActivity')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备管理',
                'verbose_name_plural': '设备管理',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('slug', models.IntegerField(choices=[(1, 'web或者wap'), (2, 'app1.7'), (3, 'app2.2')], db_index=True, default=1, verbose_name='项目版本')),
                ('platform', models.IntegerField(choices=[(1, 'app'), (2, 'wap'), (3, 'web')], default=1, verbose_name='项目平台')),
                ('intro', models.TextField(default='', verbose_name='项目简介')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加用户')),
            ],
            options={
                'verbose_name': 'APP自动化测试管理',
                'verbose_name_plural': 'APP自动化测试管理',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='英文名称')),
                ('step', models.CharField(max_length=256, verbose_name='测试步骤')),
                ('approach', models.CharField(max_length=256, verbose_name='定位方法')),
                ('element', models.CharField(max_length=256, verbose_name='定位元素')),
                ('content', models.TextField(blank=True, default='', verbose_name='备注')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用例管理',
                'verbose_name_plural': '用例管理',
            },
        ),
        migrations.CreateModel(
            name='Testpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='页面名称')),
                ('intro', models.TextField(default='', verbose_name='页面简介')),
                ('column', models.ManyToManyField(to='Auto_test.Column', verbose_name='归属项目')),
            ],
            options={
                'verbose_name': '页面管理',
                'verbose_name_plural': '页面管理',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='Testpage',
            field=models.ManyToManyField(to='Auto_test.Testpage', verbose_name='归属页面'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auto_test.Column'),
        ),
    ]
